import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Upload, FileType2, CheckCircle2, AlertCircle, Sparkles } from "lucide-react";
import { ACCEPTED_DOCUMENTS, extractDocument, getDocumentLabel } from "../../services/documentService";
import { getCurrentDocumentId, getDocument, saveDocument, setCurrentDocumentId } from "../../services/documentApi";
import "./PDFReader.css";

function PDFReader(){
  const navigate=useNavigate(); const fileInputRef=useRef(null); const [documentData,setDocumentData]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{const id=getCurrentDocumentId();if(!id)return;setLoading(true);getDocument(id).then(setDocumentData).catch(e=>{setError(e.message);setCurrentDocumentId(null)}).finally(()=>setLoading(false));},[]);
  const handleFile=async(file)=>{if(!file)return;setError("");setLoading(true);try{const extracted=await extractDocument(file);const doc=await saveDocument({name:file.name,size:file.size,mimeType:file.type||"",type:extracted.type,format:extracted.format,pageCount:extracted.pageCount,pages:extracted.pages,text:extracted.text});setDocumentData({...doc,text:extracted.text});setCurrentDocumentId(doc.id);window.dispatchEvent(new Event("documentsUpdated"));window.dispatchEvent(new Event("currentDocumentUpdated"));}catch(e){console.error(e);setError(e.message||"Something went wrong while reading the document.")}finally{setLoading(false)}};
  const formatFileSize=(bytes)=>{if(!bytes)return"0 KB";const units=["B","KB","MB","GB"];const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),units.length-1);return `${(bytes/Math.pow(1024,i)).toFixed(i===0?0:1)} ${units[i]}`};
  return <div className="pdf-reader-page"><header className="pdf-reader-header"><div className="pdf-reader-eyebrow">DOCUMENT READER</div><h1 className="pdf-reader-title">Read a document</h1><p className="pdf-reader-subtitle">Upload a document and it will be saved privately to your Marginal account.</p></header><main className="pdf-reader-main"><input ref={fileInputRef} type="file" accept={ACCEPTED_DOCUMENTS} onChange={e=>{const f=e.target.files?.[0];if(f)handleFile(f);e.target.value=""}} className="pdf-file-input" aria-label="Choose a document"/>{!documentData&&!loading&&<div className="pdf-upload-card"><div className="pdf-upload-icon"><Upload size={26}/></div><h2>Upload your study material</h2><p>PDF, Word (.docx), TXT, Markdown, and RTF files are supported.</p><button className="pdf-select-button" onClick={()=>fileInputRef.current?.click()}><Upload size={16}/>Select document</button><div className="pdf-supported-text">Private to your account · Supported: PDF · DOCX · TXT · MD · RTF</div></div>}{loading&&<div className="pdf-loading-card"><div className="pdf-spinner"/><div className="pdf-loading-title">Reading your document...</div><div className="pdf-loading-text">Extracting and securely saving readable text.</div></div>}{error&&<div className="pdf-error"><AlertCircle size={20} className="pdf-error-icon"/><div><div className="pdf-error-title">Couldn&apos;t load the document</div><div className="pdf-error-message">{error}</div></div></div>}{documentData&&!loading&&<div className="pdf-document"><div className="pdf-document-card"><div className="pdf-document-icon"><FileType2 size={21}/></div><div className="pdf-document-info"><div className="pdf-document-name">{documentData.name}</div><div className="pdf-document-meta">{documentData.format||getDocumentLabel(documentData.type)}{documentData.pageCount>0?` · ${documentData.pageCount} pages`:""}{` · ${formatFileSize(documentData.size)}`}</div></div><CheckCircle2 className="pdf-success-icon"/></div><div className="pdf-change-file"><button className="pdf-secondary-button" onClick={()=>fileInputRef.current?.click()}><Upload size={15}/>Choose another document</button></div><section className="pdf-text-card"><div className="pdf-section-label">DOCUMENT CONTENT</div><h2>Extracted text</h2><p>This content is stored in your private account and is used by Marginal&apos;s study tools.</p><div className="pdf-text-container">{documentData.text}</div></section><div className="pdf-summary-action"><div className="pdf-summary-info"><div className="pdf-summary-label">READY TO STUDY?</div><p>Generate a study summary from this document.</p></div><button className="pdf-summary-button" onClick={()=>navigate("/summary")}><Sparkles size={17}/>Summarize Document</button></div></div>}</main></div>;
}
export default PDFReader;
